---
title: "Brand/Generic Table"
---

- [ADHD Medication Chart](https://www.adhdmedicationguide.com/)

- [Asthma and COPD Medication Chart](https://www.lung.org/getmedia/e6be8c67-a793-44a8-bd7c-96629e57c20d/respiratory-medication-chart) (and unaffiliated [interactive chart](https://www.wheezypuff.com/))

- [HIV Medication Chart](https://aidsetc.org/sites/default/files/media/document/2022-11/HIV%20Medication%20Chart_August%202022.pdf)

- [Equianalgesic Doses of Opioid Analgesics](https://www.merckmanuals.com/professional/multimedia/table/equianalgesic-doses-of-opioid-analgesics)

```{r, include=FALSE}
library(tidyverse)
library(DT)

#print("HI!")
```

```{r, echo=FALSE, message=FALSE}
## Load CSV
## Note: If you encounter issues with characters, try resaving the
## CSV as a UTF-8 CSV. Excel... does not like interpreting as UTF-8
## Find the bad UTF-8 lines
# library("xfun")
# read_utf8("brand-generic.csv")
data <- read_csv("brand-generic.csv", comment = "#")

## Need to keep 1st column when doing buttons so the CSV renders properly
datatable(data,
    rownames=FALSE,
    escape = FALSE,
## Search builder is helpful with 3+ columns
#    extensions = c('Responsive', 'Buttons', 'SearchBuilder'), 
   extensions = c('Responsive', 'Buttons'), 
    options = list(
    dom = 'QBfrtip',
    pageLength = 20,
    class = 'stripe',
##    buttons = c('copy', 'csv', 'excel', 'pdf', 'print')),
    buttons = list(
      'copy', 'csv', 'excel',
      list(extend = 'pdf', 
           orientation = 'landscape',
           exportoptions=list(pageSize='LEGAL'#,
#           customize = JS("function(doc){doc.styles.tableHeader.color='purple';}")
                )),
      'print')
))

```
